//
//  SearchCharatersModels.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 7/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchCharaters
{
  // MARK: Use cases
  
  enum FetchSearch
  {
    struct Request:Encodable
    {
        var name:String
    }
    struct Response
    {
        var characters:[Character]
    }
    struct ViewModel
    {
        struct DisplaySearchResult {
            
            var name:String
        }
        var displaySearchResult: [DisplaySearchResult]
    }
  }
}
