//
//  SearchCharatersInteractor.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 7/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharatersBusinessLogic
{
  func fetchSearchResult()
}

protocol SearchCharatersDataStore
{
    var seachText:String? {get set}
    var characters:[Character]? {get set}
}

class SearchCharatersInteractor: SearchCharatersBusinessLogic, SearchCharatersDataStore
{
    var characters: [Character]?
    
    var seachText: String?  {
        didSet{
            self.fetchSearchResult()
        }
    }
  var presenter: SearchCharatersPresentationLogic?
  var charactersWorker: CharacterWorkers = CharacterWorkers(charactersService: CharacterService())
 
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchSearchResult(){
    
        let request = SearchCharaters.FetchSearch.Request(name: seachText ?? "")
        charactersWorker.searchCharacters(request: request, completionHandler: { (characters, error) in
            
            if characters != nil {

                self.characters = characters!
                let reponse = SearchCharaters.FetchSearch.Response(characters: characters!)
                self.presenter?.presentFetchedSearchResult(response: reponse)
            }
            
        })

  }
}
