//
//  ListCharactersPresenter.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersPresentationLogic
{
  func presentSomething(response: ListCharacters.Something.Response)
}

class ListCharactersPresenter: ListCharactersPresentationLogic
{
  weak var viewController: ListCharactersDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListCharacters.Something.Response)
  {
    let viewModel = ListCharacters.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
