//
//  ListCharactersWorker.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListCharactersWorker
{
  func doSomeWork()
  {
  }
    func fetchCharacters(completionHandler: @escaping ([Character]) -> Void){
        
    }
}
