//
//  ListCharactersInteractor.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersBusinessLogic
{
  func doSomething(request: ListCharacters.Something.Request)
}

protocol ListCharactersDataStore
{
  //var name: String { get set }
}

class ListCharactersInteractor: ListCharactersBusinessLogic, ListCharactersDataStore
{
  var presenter: ListCharactersPresentationLogic?
  var worker: ListCharactersWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListCharacters.Something.Request)
  {
    worker = ListCharactersWorker()
    worker?.doSomeWork()
    
    let response = ListCharacters.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
