//
//  ListCharactersPresenter.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersPresentationLogic
{
  func presentFetchedCharacters(response: ListCharacters.FetchCharacters.Response)
}

class ListCharactersPresenter: ListCharactersPresentationLogic
{
  weak var viewController: ListCharactersDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedCharacters(response: ListCharacters.FetchCharacters.Response)
  {
    var displayedCharacters: [ListCharacters.FetchCharacters.ViewModel.DisplayedCharacter] = []
    
    for character in response.characters{
        
        guard let imageURL = character.imageURL else{
            return
        }
        let displayCharacter = ListCharacters.FetchCharacters.ViewModel.DisplayedCharacter(imageURL: imageURL)
        displayedCharacters.append(displayCharacter)
    }
    
    let viewModel = ListCharacters.FetchCharacters.ViewModel(displayedCharacters: displayedCharacters)
    viewController?.displayFetchedCharacters(viewModel: viewModel)
  }
}
