//
//  ListCharactersModels.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListCharacters
{
  // MARK: Use cases
  
  enum FetchCharacters
  {
    struct Request:Encodable
    {
    }
    struct Response
    {
        var characters:[Character]
    }
    struct ViewModel
    {
        struct DisplayedCharacter {
            
            var imageURL:String
        }
        var displayedCharacters: [DisplayedCharacter]
    }
  }
}
