//
//  DetailCharacterInteractor.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 28/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailCharacterBusinessLogic
{
  func doSomething(request: DetailCharacter.Something.Request)
}

protocol DetailCharacterDataStore
{
  //var name: String { get set }
}

class DetailCharacterInteractor: DetailCharacterBusinessLogic, DetailCharacterDataStore
{
  var presenter: DetailCharacterPresentationLogic?
  var worker: DetailCharacterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DetailCharacter.Something.Request)
  {
    worker = DetailCharacterWorker()
    worker?.doSomeWork()
    
    let response = DetailCharacter.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
