//
//  ListCharactersPresenter.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersPresentationLogic
{
    func presentFetchedCharacters(response: ListCharacters.FetchCharacters.Response)
    func characterCellSize()->CGSize
    func presentSelectedSearchKeyWord(selectedSearch:String)
}

class ListCharactersPresenter: ListCharactersPresentationLogic
{
  weak var viewController: ListCharactersDisplayLogic?
  
   // MARK: Display
    func characterCellSize()->CGSize {
        
        guard let screenSize = UIApplication.shared.windows.first?.frame.size else{
            return CGSize.zero
        }
        
        let numberOfItemPerRow:CGFloat = 3
        let gap:CGFloat = 8
        let sectionInsets:CGFloat = 16
        let width = (screenSize.width - gap*(numberOfItemPerRow-1) - (sectionInsets * 2))/numberOfItemPerRow
        let height = width
        
        return CGSize(width: width, height: height)
    }
  //MARK: SearchResult
    func presentSelectedSearchKeyWord(selectedSearch:String){
         viewController?.displaySelectedSearchText(searchText: selectedSearch)
    }
  // MARK: Fetch
  
  func presentFetchedCharacters(response: ListCharacters.FetchCharacters.Response)
  {
    var displayedCharacters: [ListCharacters.FetchCharacters.ViewModel.DisplayedCharacter] = []
    
    for character in response.characters{
        
        guard let imageURL = character.imageURL else{
            return
        }
        let displayCharacter = ListCharacters.FetchCharacters.ViewModel.DisplayedCharacter(imageURL: imageURL)
        displayedCharacters.append(displayCharacter)
    }
    
    let viewModel = ListCharacters.FetchCharacters.ViewModel(displayedCharacters: displayedCharacters)
    viewController?.displayFetchedCharacters(viewModel: viewModel)
  }
}
