//
//  ListCharactersInteractor.swift
//  RickMorty_CleanSwift
//
//  Created by Nithi Kulasiriswatdi on 4/8/2563 BE.
//  Copyright (c) 2563 Nithi Kulasiriswatdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCharactersBusinessLogic
{
    func fetchCharacters(request: ListCharacters.FetchCharacters.Request)
    func getCellSize() -> CGSize
}

protocol ListCharactersDataStore
{
    var searchText: String? { get set }
    var characters:[Character]? { get set}
    
}

class ListCharactersInteractor: ListCharactersBusinessLogic, ListCharactersDataStore
{
    var searchText: String? {
        didSet{
            self.presenter?.presentSelectedSearchKeyWord(selectedSearch: searchText ?? "")
        }
    }
  var presenter: ListCharactersPresentationLogic?
    
  var charactersWorker: CharacterWorkers = CharacterWorkers(charactersService: CharacterService())
  var characters: [Character]?
  // MARK: Display
    func getCellSize() -> CGSize{
        
        return presenter?.characterCellSize() ?? CGSize.zero
    }
  // MARK: Fetch characters
  
  func fetchCharacters(request: ListCharacters.FetchCharacters.Request) {
    charactersWorker.fetchCharacters(request: request, completionHandler: { (characters, error) in
        
        if characters != nil {
            
            self.characters = characters!
            let reponse = ListCharacters.FetchCharacters.Response(characters: characters!)
            self.presenter?.presentFetchedCharacters(response: reponse)
        }
        
    })
    
  }
}
